### ISSUE TITLE
Add `code.mil` tag to project

### ISSUE THREAD

**Issue by jordangov** [deptofdefense/anet#757]
Hi folks! I would like to add the `code.mil` tag to this project. It would identify it as a DoD open source project and allow it to come up in a [tag search](https://github.com/topics/code-mil). I am happy to add the tag myself, but wanted to get a couple folks to buy in as well. Thoughts? I'm happy to answer any questions!

@nickjs @hunterp @nickheiner @tomberek

**Comment by hunterp** [comment]
Yup, sounds fine by me. Go for it!

**Comment by jordangov** [comment]
👍 
(If anyone wants to discuss, let me know... we can always remove it if necessary.)
